name: Build and Deploy herbiv
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Install vue-cli-service
        run: npm install -g @vue/cli
      - name: vue-cli-service build
        run: vue-cli-service build
      - name: Deploy
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "拷贝完成"
        with:
          host: ${{ secrets.USER_HOST }}
          user: ${{ secrets.USER_NAME }}
          pass: ${{ secrets.HUAWEI_PASS }}
          connect_timeout: 10s
          local: './dist/*'
          remote: /www/herbiv-vue/